"""Migration

Revision ID: de5a13c9fd75
Revises: c55bd8c1399d
Create Date: 2024-10-15 02:16:13.714789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de5a13c9fd75'
down_revision = 'c55bd8c1399d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Chat',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('sender_name', sa.Integer(), nullable=False),
    sa.Column('receiver_name', sa.Integer(), nullable=False),
    sa.Column('follower', sa.Boolean(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receiver_name'),
    sa.UniqueConstraint('sender_name')
    )
    op.create_table('Content',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('content_id')
    )
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_index('receiver_name')
        batch_op.drop_index('sender_name')

    op.drop_table('chat')
    op.drop_table('content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('content_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('content_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('chat',
    sa.Column('id', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('sender_name', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_name', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('follower', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('content_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('sent_at', mysql.DATETIME(), nullable=False),
    sa.Column('received_at', mysql.DATETIME(), nullable=False),
    sa.Column('read_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.create_index('sender_name', ['sender_name'], unique=True)
        batch_op.create_index('receiver_name', ['receiver_name'], unique=True)

    op.drop_table('Content')
    op.drop_table('Chat')
    # ### end Alembic commands ###
